In [9]:
import pandas as pd
import spacy

In [4]:
data = pd.read_csv('offensive_comment_small.csv', sep=';')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             10000 non-null  int64
 1   comment_text   10000 non-null  str
 2   toxic          10000 non-null  int64
 3   severe_toxic   10000 non-null  int64
 4   obscene        10000 non-null  int64
 5   threat         10000 non-null  int64
 6   insult         10000 non-null  int64
 7   identity_hate  10000 non-null  int64
dtypes: int64(7), str(1)
memory usage: 625.1 KB

In [5]:
data.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,86236166566,How can Ceha use words POV in every other sent...,0,0,0,0,0,0
1,67516955649,Blah... Childlove movement needs serious work ...,0,0,0,0,0,0
2,22144619496,"WTH DUDE Deleting my articles, you got no bloo...",0,0,0,0,1,0
3,10428262239,"'""I''ve added a citation for Epicurus being th...",0,0,0,0,0,0
4,82779776033,Violation Your recent revert on Pro-life is in...,0,0,0,0,0,0

In [15]:
nlp = spacy.load("en_core_web_sm", disable=["ner"])

def clean_text(text):
  tab_result = []
  # Ne garder que les LEMME, enlever les STOPWORDS et les mots de moins de 2 charactères
  doc = nlp(text)
  for token in doc :
    if token.is_stop == False and len(token.text)>2:
      tab_result.append(token.lemma_)
  # A vous de coder
  return tab_result

# modifier la phrase
clean_text("This IS a test, we are currently in a big data lesson and we try spacy")

['test', 'currently', 'big', 'data', 'lesson', 'try', 'spacy']

In [17]:
data['clean_comment'] = data['comment_text'].apply(clean_text)
data.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,clean_comment
0,86236166566,How can Ceha use words POV in every other sent...,0,0,0,0,0,0,"[Ceha, use, word, POV, sentence, ban, not?here..."
1,67516955649,Blah... Childlove movement needs serious work ...,0,0,0,0,0,0,"[Blah, ..., Childlove, movement, need, work, s..."
2,22144619496,"WTH DUDE Deleting my articles, you got no bloo...",0,0,0,0,1,0,"[WTH, DUDE, delete, article, get, bloody, righ..."
3,10428262239,"'""I''ve added a citation for Epicurus being th...",0,0,0,0,0,0,"[I''ve, add, citation, Epicurus, originator, p..."
4,82779776033,Violation Your recent revert on Pro-life is in...,0,0,0,0,0,0,"[violation, recent, revert, pro, life, direct,..."

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             10000 non-null  int64
 1   comment_text   10000 non-null  str
 2   toxic          10000 non-null  int64
 3   severe_toxic   10000 non-null  int64
 4   obscene        10000 non-null  int64
 5   threat         10000 non-null  int64
 6   insult         10000 non-null  int64
 7   identity_hate  10000 non-null  int64
 8   clean_comment  10000 non-null  object
dtypes: int64(7), object(1), str(1)
memory usage: 703.3+ KB